NumPy provides a high-performance n-dimensional array object. <br>
A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

<b>Rank</b>: Number of dimensions <br>
<b>Shape</b>: Tuple of integers giving the size of the array along each dimension

In [19]:
# Initializing a NumPy array
import numpy as np

arr = np.array([1,2,3]) # rank = 1
print(type(arr))        # prints <class 'numpy.ndarray'> 
print(arr.shape)        # prints (3,)
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.shape)       # prints (2,3)

arr3 = np.zeros((2,2))
print(arr3)
arr4 = np.ones((1,2))
print(arr4)
arr5 = np.full((2,2),7) # creates constant array
print(arr5)
i = np.eye(2)           # creates 2x2 identity matrix
print(i)

np.random.random((2,2)) # for uniformly distributed random values, 2x2 array with values b/w 0 and 1
np.random.normal(0,1,(3,3)) # for normally distributed random values, mean 0, stddev 1
np.random.randint(0,10,(3,3)) # for random integers in interval [0,10)
np.empty(3) # uninitialized with 3 integers, value is whatever exists at that memory location

<class 'numpy.ndarray'>
(3,)
(2, 3)
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313])

In [14]:
# Other initializations
import numpy as np

np.array([1, 2, 3, 4], dtype='float32') # for float
np.array([range(i, i + 3) for i in [2, 4, 6]]) # prints array([[2, 3, 4],
                                               #[4, 5, 6],
                                               #[6, 7, 8]])
np.arange(0,20,2) # linear sequence starting at 0, ending at 20, step 2
np.linspace(0,1,5) # creates array of 5 values evenly spaced between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
# Indexing NumPy arrays
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:2, 1:3] # pulls out subarray containing the first 2 rows, and columns 1 and 2; shape of b then is (2,2)
print(a[0,1])
b[0,0] = 77
print(a[0,1]) # will print 77 as b[0,0] is the same piece of data as a[0,1

c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
r1 = c[1, :] # rank 1 view of the second row of a
r2 = c[1:2, :] # rank 2 view of the second row of a
print(r1, r1.shape) # prints [5,6,7,8] (4,)
print(r2, r2.shape) # prints [[5,6,7,8]] (1,4)
c1 = c[:, 1]
c2 = c[:, 1:2]
print(c1, c1.shape)
print(c2, c2.shape)

d = np.array([[1,2],[3,4],[5,6]])
print(d[[0,1,2],[0,1,0]])  # prints [1,4,5] with shape (3,) which is equivalent to below line
print(np.array([d[0,0],d[1,1],d[2,0]]))


2
77
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


One useful trick with integer array indexing is the ability to select or mutate one element from each row of a matrix.

In [ ]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)
arr2 = np.array([0,2,0,1]) # creating array of indices
print(arr[np.arange(4),arr2]) # select one element from each row of arr using the indices in arr2, prints [1,6,7,11]
arr[np.arange(4),arr2] += 10 # mutate one element from each row of arr using the indices in arr2
print(arr)  # prints "array([[11,  2,  3],
            #                [ 4,  5, 16],
            #                [17,  8,  9],
            #                [10, 21, 12]])